
title = "This is Ben Rivera's Personal Website"
author = "Ben Rivera"
#copyright = "2020-2021"
description = "benrivera@ucdavis.edu - Benjamin.J.Rivera27@gmail.com - https://orcid.org/0000-0002-2294-6003"
profilePicture = "images/RiveraPic.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/mbjwlnza"
# Google Fonts
googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.


[[socialIcons]]
icon = "fab fa-orchid"
title = "twitter"
url = "https://twitter.com/NotBenRivera"

[[socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/NotBenRivera"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:benrivera@ucdavis.edu"